"""Install long-exposure's hooks into a vendor CLI's config.

Separate from `cli-install` on purpose. `cli-install` writes adapter files
*into the project*; this writes into files the operator owns and curates —
`~/.claude/settings.json`, `~/.codex/hooks.json` — or their project-local
equivalents. Adopting the harness should never silently edit those, so this
is its own opt-in command and it always says what it touched.

## What gets written

One shim per hook per vendor, plus a config entry pointing at it. The shim
exists so the config does not have to encode a `PYTHONPATH` it cannot set:
vendor hook configs have no `env` field, so the interpreter and the import
path are baked into a two-line script instead.

    <dir>/hooks/long-exposure-<hook>.sh   ->  exec <python> -m long_exposure.hooks.<hook>

## Merging, not overwriting

An operator's settings file probably already has hooks in it. Entries are
matched by the `command` containing `long_exposure.hooks.<name>`, so
re-running the installer replaces long-exposure's own entries and leaves
everything else alone. `uninstall` removes exactly those.

## Vendor mapping

| Hook | Claude | Codex | Gemini |
|---|---|---|---|
| envelope | `Stop` | `Stop` | — (no event) |
| compaction | `PreCompact`, `PostCompact` | same | — (no event) |

Where Gemini has no equivalent the hook is skipped and the installer says so
rather than writing something that will not fire.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

VENDORS = ("claude", "codex", "gemini")

# hook name -> {vendor: [event names]}. An empty list means "this vendor has
# no equivalent event"; the installer reports it as skipped.
HOOK_EVENTS: dict[str, dict[str, tuple[str, ...]]] = {
    "envelope": {
        "claude": ("Stop",),
        "codex": ("Stop",),
        "gemini": (),
    },
    "compaction": {
        "claude": ("PreCompact", "PostCompact"),
        "codex": ("PreCompact", "PostCompact"),
        "gemini": (),
    },
}

# The tool-name matcher per hook. Neither remaining hook is tool-scoped, so
# both match every occurrence of their event.
HOOK_MATCHER: dict[str, str] = {
    "envelope": "",
    "compaction": "",
}

HOOK_TIMEOUT = {"envelope": 20, "compaction": 10}

# How an entry is recognised as ours on re-install and uninstall. The config
# stores the SHIM PATH, not the module name — the module name only appears
# inside the shim's text — so the marker has to be the shim's filename stem.
# Getting this wrong meant uninstall silently left our entries behind and a
# re-install duplicated them; the tests now pin both.
SHIM_PREFIX = "long-exposure-"
MARKER = SHIM_PREFIX


def vendor_dir(vendor: str, directory: Path | None = None) -> Path:
    """Where this vendor keeps its config.

    `directory` selects the project-local form (`<dir>/.claude/`); omitting
    it selects the operator's home config, which is where a hook that should
    apply to every run belongs.
    """
    if directory is not None:
        return Path(directory).expanduser().resolve() / f".{vendor}"
    return Path.home() / f".{vendor}"


def config_path(vendor: str, directory: Path | None = None) -> Path:
    base = vendor_dir(vendor, directory)
    if vendor == "codex":
        return base / "hooks.json"
    return base / "settings.json"


def shim_path(vendor: str, hook: str, directory: Path | None = None) -> Path:
    return vendor_dir(vendor, directory) / "hooks" / f"long-exposure-{hook}.sh"


def _harness_root() -> str:
    """The harness source tree, for the shim's PYTHONPATH."""
    return str(Path(__file__).resolve().parent.parent)


def shim_text(hook: str) -> str:
    """A two-line shim: set the import path, exec the module."""
    return (
        "#!/bin/sh\n"
        "# Generated by `long-exposure hooks-install`. Safe to delete;\n"
        "# re-run the installer to restore it.\n"
        f'PYTHONPATH="{_harness_root()}${{PYTHONPATH:+:$PYTHONPATH}}" \\\n'
        f'  exec "{sys.executable}" -m long_exposure.hooks.{hook} "$@"\n'
    )


def _entry(hook: str, vendor: str, directory: Path | None) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "hooks": [{
            "type": "command",
            "command": str(shim_path(vendor, hook, directory)),
            "timeout": HOOK_TIMEOUT.get(hook, 20),
        }]
    }
    matcher = HOOK_MATCHER.get(hook, "")
    if matcher:
        entry["matcher"] = matcher
    return entry


def _our_shim_names() -> set[str]:
    return {f"{SHIM_PREFIX}{hook}.sh" for hook in HOOK_EVENTS}


def _is_ours(entry: Any) -> bool:
    """True iff this config entry points at a shim this installer wrote.

    Matched on the command's basename against the known hook names, rather
    than a loose substring, so an operator's own script that happens to live
    under a path containing "long-exposure" is never removed.
    """
    if not isinstance(entry, dict):
        return False
    names = _our_shim_names()
    for h in entry.get("hooks") or []:
        if not isinstance(h, dict):
            continue
        command = str(h.get("command", ""))
        if not command:
            continue
        if Path(command.split()[0]).name in names:
            return True
    return False


def _load(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def plan(
    vendor: str,
    hooks: tuple[str, ...],
    directory: Path | None = None,
) -> dict[str, Any]:
    """What `install` would do, without doing it."""
    events: dict[str, list[str]] = {}
    skipped: list[str] = []
    for hook in hooks:
        vendor_events = HOOK_EVENTS.get(hook, {}).get(vendor, ())
        if not vendor_events:
            skipped.append(hook)
            continue
        for event in vendor_events:
            events.setdefault(event, []).append(hook)
    return {
        "vendor": vendor,
        "config": str(config_path(vendor, directory)),
        "events": events,
        "skipped": skipped,
        "shims": [str(shim_path(vendor, h, directory))
                  for h in hooks if h not in skipped],
    }


def install(
    vendor: str,
    hooks: tuple[str, ...],
    directory: Path | None = None,
    *,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Write the shims and merge the config entries. Idempotent."""
    result = plan(vendor, hooks, directory)
    result["written"] = []
    if dry_run:
        return result

    if not result["events"]:
        # Nothing to install for this vendor — every requested hook needs an
        # event it does not have. Do not create or touch its config file:
        # the whole reason this is a separate command is that these files
        # belong to the operator.
        return result

    cfg_path = config_path(vendor, directory)
    cfg = _load(cfg_path)
    existing = cfg.get("hooks")
    hooks_block: dict[str, Any] = existing if isinstance(existing, dict) else {}

    for hook in hooks:
        if hook in result["skipped"]:
            continue
        sp = shim_path(vendor, hook, directory)
        sp.parent.mkdir(parents=True, exist_ok=True)
        sp.write_text(shim_text(hook))
        sp.chmod(0o755)
        result["written"].append(str(sp))

    for event, event_hooks in result["events"].items():
        # Drop our previous entries for this event, keep the operator's.
        current = hooks_block.get(event)
        kept = [e for e in current if not _is_ours(e)] if isinstance(current, list) else []
        hooks_block[event] = kept + [
            _entry(h, vendor, directory) for h in event_hooks
        ]

    cfg["hooks"] = hooks_block
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    if cfg_path.exists():
        backup = cfg_path.with_name(cfg_path.name + ".long-exposure-bak")
        try:
            shutil.copy2(cfg_path, backup)
            result["backup"] = str(backup)
        except OSError:
            pass
    cfg_path.write_text(json.dumps(cfg, indent=2, sort_keys=True) + "\n")
    result["written"].append(str(cfg_path))
    return result


def uninstall(vendor: str, directory: Path | None = None) -> dict[str, Any]:
    """Remove only long-exposure's entries and shims."""
    cfg_path = config_path(vendor, directory)
    cfg = _load(cfg_path)
    removed_events: list[str] = []
    block = cfg.get("hooks")
    if isinstance(block, dict):
        for event, entries in list(block.items()):
            if not isinstance(entries, list):
                continue
            kept = [e for e in entries if not _is_ours(e)]
            if len(kept) != len(entries):
                removed_events.append(event)
            if kept:
                block[event] = kept
            else:
                block.pop(event, None)
        if block:
            cfg["hooks"] = block
        else:
            cfg.pop("hooks", None)
        try:
            cfg_path.write_text(json.dumps(cfg, indent=2, sort_keys=True) + "\n")
        except OSError:
            pass
    removed_shims = []
    for hook in HOOK_EVENTS:
        sp = shim_path(vendor, hook, directory)
        try:
            if sp.is_file():
                sp.unlink()
                removed_shims.append(str(sp))
        except OSError:
            pass
    return {"vendor": vendor, "events": removed_events, "shims": removed_shims}


# ---------------------------------------------------------------------------
# Shim smoke check
# ---------------------------------------------------------------------------


def verify(
    vendor: str = "claude",
    hook: str = "envelope",
    directory: Path | None = None,
) -> tuple[bool, str]:
    """Check an installed shim actually runs. Returns (ok, detail).

    A smoke check, not a gate. A config entry existing does not mean the
    script runs: the shim can point at a moved checkout, the interpreter can
    be gone, the execute bit can be lost. Both remaining hooks are
    non-blocking, so a broken one costs an unenforced envelope nudge or a
    missing log line — worth knowing about, not worth refusing to start a
    run over.

    The payload is benign on purpose: a complete output block for the
    envelope, a plain compaction event for the other. A healthy shim exits 0
    and says nothing.
    """
    sp = shim_path(vendor, hook, directory)
    if not sp.is_file():
        return False, f"{hook} shim missing: {sp}"
    if not os.access(sp, os.X_OK):
        return False, f"{hook} shim is not executable: {sp}"

    if hook == "envelope":
        payload = {
            "hook_event_name": "Stop",
            "session_id": "verify",
            "last_assistant_message": "[OUTPUT: x]\nbody\n[END OUTPUT: x]",
        }
    else:
        payload = {
            "hook_event_name": "PreCompact",
            "session_id": "verify",
            "trigger_reason": "verify",
        }
    try:
        proc = subprocess.run(
            [str(sp)], input=json.dumps(payload),
            capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError) as e:
        return False, f"{hook} shim failed to run: {e!r}"

    if proc.returncode != 0:
        return False, (
            f"{hook} shim exited {proc.returncode}: "
            f"{(proc.stderr or '').strip()[:200]}"
        )
    out = (proc.stdout or "").strip()
    if out:
        try:
            json.loads(out)
        except ValueError:
            return False, f"{hook} shim emitted non-JSON: {out[:200]!r}"
    return True, f"{hook} shim runs: {sp}"


def render_summary(result: dict[str, Any]) -> str:
    lines = [f"[hooks] {result['vendor']}: {result['config']}"]
    for event, hooks in sorted((result.get("events") or {}).items()):
        lines.append(f"  {event:<14} {', '.join(hooks)}")
    for hook in result.get("skipped") or []:
        lines.append(f"  (skipped)      {hook} — no equivalent event on this CLI")
    if result.get("backup"):
        lines.append(f"  backup:        {result['backup']}")
    return "\n".join(lines)
